### ISSUE TITLE
for td-agent 4 installation fails oracle lnx/rhel

### ISSUE THREAD

**Issue by mayur-oci** [fluent/fluentd-docs-gitbook#222]
# td-agent 4
$ curl -L https://toolbelt.treasuredata.com/sh/install-redhat-td-agent4.sh | sh

https://docs.fluentd.org/installation/install-by-rpm

**Comment by cosmo0920** [comment]
Could you share your error log?
Just sharing reproducing step does not help.

**Comment by nmaludy** [comment]
@cosmo0920 i figured out what was going on here because i have the same problem.

You end up getting an error:
```shell
http://packages.treasuredata.com/4/redhat/7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
```

I tried visiting that page and it indeed did fail. 

The repo file is setup as:
```
[treasuredata]
name=TreasureData
baseurl=http://packages.treasuredata.com/4/redhat/\$releasever/\$basearch
gpgcheck=1
gpgkey=https://packages.treasuredata.com/GPG-KEY-td-agent
```

I figured out what was going wrong by comparing what the v3 agent did and it had a repo setup of

```
[treasuredata]
name=TreasureData
baseurl=http://packages.treasuredata.com/3/redhat/\$releasever/\$basearch
gpgcheck=1
gpgkey=https://packages.treasuredata.com/GPG-KEY-td-agent
```

Looks very similar, so i tried going to http://packages.treasuredata.com/3/redhat/7Server/x86_64/repodata/repomd.xml

When going there i noticed it automatically redirected to http://packages.treasuredata.com/3/redhat/7/x86_64/repodata/repomd.xml

It looks like the v4 repos are missing this redirect/symlink.

Any chance you could get it added?

**Comment by repeatedly** [comment]
Add redirect for `7Server` and `8Server`. Closed
